name: auto_merge

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'
    # cron表达式,每天晚上12点执行一次，actions任务时区为UTC时区。 


jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
        lfs: true

    - name: Set git identity
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
    - name: Load upstream commits
      run: |
        #git fetch https://github.com/FilipePS/Traduzir-paginas-web.git master
        #git reset --hard origin/master
        #git pull https://github.com/FilipePS/Traduzir-paginas-web.git --log --no-commit --rebase
        #git add *
        #git rebase --continue
        git pull https://github.com/FilipePS/Traduzir-paginas-web.git --log --no-commit --rebase
    - name: Apply commit changes
      run: |
        if [ -f ./.git/MERGE_MSG ]; then
        mkdir ./tmp && cp ./.git/MERGE_MSG ./tmp/message
        sed -i "1c [bot] AutoMerging: merge all upstream's changes:" ./tmp/message
        sed -i '/^\#.*/d' ./tmp/message
        git commit --file="./tmp/message"
        else
        echo "There is no merge commits."
        fi
    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: master
        TZ: Asia/Shanghai
      run: git push origin $DOWNSTREAM_BRANCH -f
